import type { NextPage } from 'next'
import Head from 'next/head'
import HomePage from "@/modules/home/presentation/pages/home"
import localize from '@/core/localization'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
       <title>{localize("HOME__TITLE")}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePage />
    </div>
  )
}

export default Home
